# Generated by Django 6.0 on 2025-12-09 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('previous_activity_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_next', to='courseware.learningactivity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('learningactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.learningactivity')),
                ('due_date', models.DateTimeField()),
                ('max_points', models.PositiveIntegerField(default=100)),
                ('allow_file_upload', models.BooleanField(default=True)),
                ('allow_code_editor', models.BooleanField(default=False, help_text='Enable Monaco Editor for Verilog/C')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courseware.learningactivity',),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('learningactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.learningactivity')),
                ('topic', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courseware.learningactivity',),
        ),
        migrations.CreateModel(
            name='PDFResource',
            fields=[
                ('learningactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.learningactivity')),
                ('file', models.FileField(upload_to='course_pdfs/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courseware.learningactivity',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('learningactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.learningactivity')),
                ('time_limit_minutes', models.PositiveIntegerField(default=30)),
                ('pass_score', models.PositiveIntegerField(default=60)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courseware.learningactivity',),
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('learningactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courseware.learningactivity')),
                ('video_url', models.URLField(help_text='Link to video file or stream')),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courseware.learningactivity',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courseware.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courseware.unit'),
        ),
    ]
