# Generated by Django 6.0 on 2025-12-09 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubmission',
            name='members',
            field=models.ManyToManyField(related_name='group_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
