from django.db import models
from django.utils import timezone
from apps.core.models import User, Course

class AttendanceSession(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='attendance_sessions')
    code = models.CharField(max_length=4, help_text="4-Digit Code generated by teacher")
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    duration_minutes = models.PositiveIntegerField(default=5)

    def is_valid(self):
        now = timezone.now()
        diff = now - self.created_at
        return diff.total_seconds() < (self.duration_minutes * 60)

    def __str__(self):
        return f"{self.course.course_code} Session {self.code}"

class AttendanceRecord(models.Model):
    class Status(models.TextChoices):
        PRESENT = 'PRESENT', 'Present'
        ABSENT = 'ABSENT', 'Absent'
        LATE = 'LATE', 'Late'

    session = models.ForeignKey(AttendanceSession, on_delete=models.CASCADE, related_name='records')
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='attendance_records')
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.ABSENT)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('session', 'student')

    def __str__(self):
        return f"{self.student.username} - {self.status}"
